### ISSUE TITLE
Question: Why another repo?

### ISSUE THREAD

**Issue by sirreal** [Automattic/color-studio#1]
Was including this package as part of the [Calypso](https://github.com/Automattic/wp-calypso/) repo considered?

If so, why was the decision made to make a new and independent repo?

If not, let's consider moving it into Calypso and publishing it as a package from the monorepo!

There is non-trivial and intentional effort being put into investing more effort on a single codebase and reaping multiplied rewards as a result. Context: p3N5Fy-uu-p2

cc: @Automattic/team-calypso

**Comment by porada** [comment]
It was developed in isolation and as a successor to an older color tool, so that’s why it’s been living in a separate repo. I’d love for it to become a part of Calypso, though.

**Comment by porada** [comment]
Question: If we merge the repo, will it become more difficult for WordPress.org to use the palette?

**Comment by sirreal** [comment]
> I’d love for it to become a part of Calypso, though.

Let's make it happen 😁 👍 

> Question: If we merge the repo, will it become more difficult for WordPress.org to use the palette?

It appears that this is published and consumed via npm. That would remain exactly the same. Are there other concerns?

**Comment by sirreal** [comment]
@porada We've begun looking at bringing this into Calypso (https://github.com/Automattic/wp-calypso/pull/29070) but there are some housekeeping questions we need to consider.

This is unpublished, is that correct? Is there a plan for how and where to publish this? Will it be published under an npm org?

There seem to be 3 main pieces to this repo:
- Color values for consumption from JavaScript and Sass.
- A sketch plugin
- Tooling and structure to produce a documentation site.

It may not make sense for all of those pieces to move into Calypso proper. A path forward might look like:

- Color values move into Calypso and are published as an easily consumable and small module.
- This repository depends on the published package and uses that to produce and host the sketch plugin and documentation site.

How would a setup like that sound?

cc: @Automattic/team-calypso

**Comment by simison** [comment]
> This repository also contains the build tool that generates all these colors. While it (including its dependencies) doesn’t have to be exposed to npm, it should be a part of the repository that contains the distributable files.

That's okay and would remain working well in Calypso monorepo.

>In the internal announcement, I mentioned that color-studio is a legacy name and it can always be changed. Now would be the best time to do that, right?

Totally! I wouldn't let things like names slow things down. It's just a name and easy to change at any point. :-)

To me it seems like easiest path forward would be to:
- Move the whole repo to [Calypso `/packages`](https://github.com/Automattic/wp-calypso/tree/6a0b2aa05d4e9c026932d5259c6cb89849c5c866/packages) folder. I think there's a way to do that so that you'd keep git history, if it matters.
- Remove XO integration
- Run Calypso's Prettier and eslint in these files to make everything ready for Calypso
- Hook build and test scripts to run together with Calypso (other packages in Calypso have examples of this)
- Publish the package to NPM
- Transfer issues from this repo to Calypso
- Archive this repo

See [Calypso monorepo docs](https://github.com/Automattic/wp-calypso/blob/6a0b2aa05d4e9c026932d5259c6cb89849c5c866/docs/monorepo.md#readme) for guidance and ping @blowery  :-) :wave:

This repository is at an odd state where Calypso is its primary consumer (as far as I know?) and this isn't published to NPM. We're about to bring this as a dependency to Jetpack as well (https://github.com/Automattic/jetpack/issues/11478).

Let's get this sorted out sooner than later, before folks who are familiar with this project move on to other adventures. :-) What do you think, @porada ? I'm happy to help with guidance/connect you with the right people if needed.

**Comment by blowery** [comment]
This is probably a contrarian opinion, but I think leaving this where it is might make the most sense, at least in the short term. Compared to the list of points on how to move to Calypso, the only thing we'd have to do with the current setup is to publish the package to NPM and update consumers to use it. 

If we did move it to Calypso, we'd probably want to separate out the generation of the various formats from the site generation. 

How tied are you to the current URL for the demo site? How tied are you to the demo site in general? We could move the color palette demo into Calypso's devdocs...

**Comment by simison** [comment]
Valid points!

I think a good question to help decide is if we expect to maintain this package well and frequently and if the amount of work double-maintaining this + Calypso tooling is more work than doing the migration now?

**Comment by simison** [comment]
>How tied are you to the current URL for the demo site? How tied are you to the demo site in general? We could move the color palette demo into Calypso's devdocs...

I'd also add what is optimal place in terms of discoverability of these docs?

**Comment by porada** [comment]
Apologies for the lack of response—I was on holiday.

> If we did move it to Calypso, we'd probably want to separate out the generation of the various formats from the site generation.

Yep. On top of that, leaving this repo as a separate entity allows us to develop the colors and the formats independently, without the work–in–progress deliverables being referenced and automatically picked up in Calypso.

> I think a good question to help decide is if we expect to maintain this package well and frequently and if the amount of work double-maintaining this + Calypso tooling is more work than doing the migration now?

I think performing the migration will be more cumbersome than explicitly bumping the dependency version number when necessary.

> How tied are you to the current URL for the demo site? How tied are you to the demo site in general? We could move the color palette demo into Calypso's devdocs...

Having the demo in this repo makes it easier to preview the work during development, but I’m fine with publishing it as a part of Calypso docs.

**Comment by porada** [comment]
I’ve been working on a new iteration of the palette. I can tell that the independent felt nice, but it’s the interoperability between the very color changes and the docs (and now also the examples) that was the key.

Given the benefits and the fact that moving this inside Calypso’s umbrella would require additional efforts, I’m closing this for now. We can always revisit.

**Comment by porada** [comment]
BTW, Color Studio is available on `npm` as `color-studio`. The old version can be referenced as `color-studio@1.0.5` while the new version I mentioned will be published on `npm` next week. P2 to follow shortly.
